---
name: Mopidy
version: dev
slug: mopidy
panel_icon: mdi:music-circle
description: Mopidy is an extensible music server
url: https://github.com/hassio-addons/addon-mopidy
codenotary: codenotary@frenck.dev
ingress: true
ingress_entry: iris/
ingress_stream: true
init: false
arch:
  - amd64
auth_api: true
audio: true
ports:
  6600/tcp: 6600
  5555/udp: 5555
  80/tcp: null
  1704/tcp: 1704
  1705/tcp: 1705
  1780/tcp: 1780
ports_description:
  6600/tcp: Mopidy
  5555/udp: Autoaudiosink
  80/tcp: Web interface (Not required for Ingress)
  1704/tcp: Snapserver
  1705/tcp: Snapserver RPC
  1780/tcp: Snapserver Web
map:
  - config
  - share:rw
  - ssl
  - media
options:
  stream:
    streams:
      - pipe:///share/snapfifo/librespot?name=SpotifyConnect&sampleformat=44100:16:2
      - pipe:///share/snapfifo/mopidy?name=Mopidy&sampleformat=44100:16:2
      - tcp://0.0.0.0?port=4953&name=snapbroadcast
    buffer: "1000"
    codec: flac
    send_to_muted: "false"
    sampleformat: "48000:16:2"
  http:
    enabled: "true"
    doc_root: " "
  tcp:
    enabled: "true"
  logging:
    enabled: "true"
  server:
    threads: "-1"
    datadir: "/share/snapcast/"
  system_packages: []
  python_packages: []
  settings: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  system_packages:
    - str
  python_packages:
    - str
  settings:
    - name: str
      value: str
  leave_front_door_open: bool?
  stream:
    streams:
      - str
    buffer: int
    codec: str
    send_to_muted: str
    sampleformat: str
  http:
    enabled: str
    doc_root: str
  tcp:
    enabled: str
  logging:
    enabled: str
  server:
    threads: int
    datadir: str
